### ISSUE TITLE
Docker command not found - MacOs X 

### ISSUE THREAD

**Issue by NightWalker1230** [ptrumpis/snap-camera-server#32] opened 2023-06-03 17:43 UTC
I'm getting a docker command not found after the docker compose up run on the terminal when following the 'Installing Snap Camera Server on Mac OS' video on Youtube. Everything is working well until I get to the 'docker compose up' command.

I have restarted everything - both Terminal and my Mac. I am inside the server directory but keep getting:  docker command not found. Please help. They all have these long unhelpful solutions when I look that issue up on Google. I'm working with the last version of Mac OsX, the Apple Silicon based one, not the Intel version one. Can you help please?

Thank you,

C

**Comment by ptrumpis** [comment] 2023-06-03 19:33
Did you download and install Docker Desktop?
Can you start Docker Desktop?

**Comment by NightWalker1230** [comment] 2023-06-03 19:54
Hello, yes, I have downloaded and installed it and it was open and running each time I would open terminal and get the docker command not found error.

**Comment by ptrumpis** [comment] 2023-06-03 20:23
Try to run this command instead of just docker compose up
```
/Applications/Docker.app/Contents/Resources/bin/docker compose up
```

**Comment by NightWalker1230** [comment] 2023-06-04 05:46
Hi,

Thank you for sending this command. I keep getting this error:

docker: 'compose' is not a docker command.
See 'docker --help'

I am not sure if this has to do with some docker command update related to Mac, but it seems that it won't recognise docker compose up as a command at all. I guess there is a different command instead of this one to replace this one? Is there any such alternative docker command?

**Comment by NightWalker1230** [comment] 2023-06-04 05:58
In addition to my previous comment, I decided to look into 'docker --help', and this is what I got after I entered it:


Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Common Commands:
  run         Create and run a new container from an image
  exec        Execute a command in a running container
  ps          List containers
  build       Build an image from a Dockerfile
  pull        Download an image from a registry
  push        Upload an image to a registry
  images      List images
  login       Log in to a registry
  logout      Log out from a registry
  search      Search Docker Hub for images
  version     Show the Docker version information
  info        Display system-wide information

Management Commands:
  builder     Manage builds
  container   Manage containers
  context     Manage contexts
  extension*  Manages Docker extensions (Docker Inc., v0.2.19)
  image       Manage images
  init*       Creates Docker-related starter files for your project (Docker Inc., v0.1.0-beta.4)
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  plugin      Manage plugins
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Swarm Commands:
  swarm       Manage Swarm

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  import      Import the contents from a tarball to create a filesystem image
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  wait        Block until one or more containers stop, then print their exit codes

Invalid Plugins:
  buildx      failed to fetch metadata: fork/exec /Users/MyMac/.docker/cli-plugins/docker-buildx: no such file or directory
  compose     failed to fetch metadata: fork/exec /Users/MyMac/.docker/cli-plugins/docker-compose: no such file or directory
  dev         failed to fetch metadata: fork/exec /Users/MyMac/.docker/cli-plugins/docker-dev: no such file or directory
  sbom        failed to fetch metadata: fork/exec /Users/MyMac/.docker/cli-plugins/docker-sbom: no such file or directory
  scan        failed to fetch metadata: fork/exec /Users/MyMac/.docker/cli-plugins/docker-scan: no such file or directory
  scout       failed to fetch metadata: fork/exec /Users/MyMac/.docker/cli-plugins/docker-scout: no such file or directory

Global Options:
      --config string      Location of client config files (default
                           "/Users/MyMac/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug", "info",
                           "warn", "error", "fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/Users/MyMac/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "/Users/MyMac/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/Users/MyMac/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Run 'docker COMMAND --help' for more information on a command.

For more help on how to use Docker, head to https://docs.docker.com/go/guides/

**Comment by ptrumpis** [comment] 2023-06-04 09:29
From https://github.com/docker/for-mac/issues/6569#issuecomment-1327104470
```
mkdir -p /usr/local/lib/docker
ln -s /Applications/Docker.app/Contents/Resources/cli-plugins /usr/local/lib/docker/cli-plugins
```

This might help, but it's a docker/mac related issue and nothing I can assist you with since I can not reproduce the error.
The community forum could provide you with better help https://forums.docker.com/c/community/59

**Comment by NightWalker1230** [comment] 2023-06-04 11:50
Thank you for your help.

I've tried that instead of 'docker compose up' and this is what I am getting:

ln: /usr/local/lib/docker/cli-plugins: File exists

Is this sufficient? I see that they get a different result in the snap server video after  entry of 'docker compose up'

**Comment by NightWalker1230** [comment] 2023-06-17 12:45
Hello again, I have contacted Docker and they have instructed me to completely uninstall and then re-install Docker and the compose up command worked.

However, now when I get to the Edit your /etc/hosts file part (part 5 of configuration),  I am getting this:

  UW PICO 5.09                        File: /etc/hosts                          

66.228.41.64    studio-app.snapchat.com
66.228.41.64    studio-app.snapchat.com

# This entry was appended by Docker Desktop because `localhost` did not resolve
# to a list of addresses which included 127.0.0.1. This can happen due to a bug
# in the macOS migration assistant, or possibly because another tool has
# corrupted the file.
127.0.0.1       localhost
# End of the section appended by Docker Desktop
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
127.0.0.1       studio-app.snapchat.com

When i close Terminal after that, after I have saved that, I open Snap Camera and I can see all new filters when I look for them but when they won't stop loading when I click on them. The loading part stays forever and I can't use any therefore. Is there anything I am doing wrong that can be fixed about part 5 and the error/result I am getting?

Thanks

**Comment by ptrumpis** [comment] 2023-06-17 15:39
Did you apply the signature patch?

**Comment by NightWalker1230** [comment] 2023-06-17 18:28
Yes, I did.

Do you have any idea what's going on?

**Comment by ptrumpis** [comment] 2023-06-18 13:34
**Follow these steps**
1. Open Snap Camera
2. Select all Lenses that are not working in your app
3. Copy and attach the Snap Camera log file to this ticket

```
/Users/{YOUR_USER_NAME}/Library/Preferences/Snap/Snap Camera/Log.txt
```

**Comment by ptrumpis** [comment] 2023-06-21 19:51
I'm closing this, please open another "Lens not working" ticket if you need futher assistance.

**Closed by ptrumpis** 2023-06-21 19:51 UTC
Labels: bug
